config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'authentication' }

  root 'home#index'

  namespace :directory do
    resources :profiles, only: [:index, :show]
    resources :practices, only: [:index, :show]
  end

  namespace :admin do
    resources :users, except: [:show] do
      get 'delete'
      get 'roles'
      post 'update_roles'
    end
    resources :positions, except: [:show] do
      get 'delete'
    end
    resources :practices, except: [:show] do
      get 'delete'
      resources :memberships, path: :members, except: [:show] do
        get 'delete'
      end
    end
    resources :videos do
      get 'delete'
    end
  end

  resources :videos do
    collection do
      get :autocomplete_video_name
      post :search
    end
  end

  # mount Rop::Engine, at: '/guides', as: 'guides'
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :users
end

app/controllers/admin/positions_controller.rb
class Admin::PositionsController < ApplicationController
  include DefaultCrud

  before_action :authenticate_user!
  before_action :admin_access?

  private

  def entity_parameters
    params.require(:position).permit(:name)
  end

  def load_entity_object_by_id
    @entity_object = entity.find(params[:position_id])
  end

end

app/views/admin/positions/_delete.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Delete Position</h4>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure that you want to delete this record: <b><%= position.name %></b>?
</div>
<div class="modal-footer">
  <%= link_to 'Cancel', '#', class: 'btn btn-default', data: { dismiss: 'modal' } %>
  <%= link_to 'Delete Position', admin_position_path(position), method: :delete, remote: true,
    class: 'btn btn-danger' %>
</div>

app/views/admin/positions/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Edit Position</h4>
</div>
<div>
  <%= render 'form', position: position %>
</div>

app/views/admin/positions/_form.html.erb
<%= form_for [:admin, position], remote: true, html: { style: 'display:inline;' } do |f| %>
  <div class="modal-body">
    <div class="errors"></div>
    <div class="form-group">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn', data: { dismiss: 'modal' } %>
  </div>
<% end %>

app/views/admin/positions/_index.html.erb
<table id="positions-table" class="table table-striped table-bordered" width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% positions.each do |position| %>
    <tr>
      <td><%= position.name %></td>
      <td>
        <%= link_to edit_admin_position_path(position), remote: true,
          class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= link_to admin_position_delete_path(position), remote: true,
          class: 'btn btn-danger btn-sm' do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<script type="text/javascript">
  $(document).ready(function() {
    $('#positions-table').DataTable({
      retrieve: true,
      iDisplayLength: 50,
      columns: [
        { type: "string" },
        { orderable: false }
      ]
    });
  });
</script>

app/views/admin/positions/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">New Position</h4>
</div>
<div>
  <%= render 'form', position: position %>
</div>

app/views/admin/positions/_reload.html.erb
$("ul.errors").html("")
<% if position.errors.any? %>
  <% position.errors.full_messages.each do |message| %>
    $("div.errors").append($("<div class='alert alert-danger'/>").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $("#positions-content").html("<%= escape_javascript(render 'index', positions: positions ) %>");
  $("#positions-modal").modal("hide");
<% end %>

app/views/admin/positions/create.js.erb
<%= render 'reload', position: @entity_object, positions: @all_entity_objects %>

app/views/admin/positions/delete.js.erb
$("#positions-modal-content")
  .html("<%= escape_javascript(render 'delete', position: @entity_object ) %>");
$("#positions-modal").modal();

app/views/admin/positions/destroy.js.erb
<%= render 'reload', position: @entity_object, positions: @all_entity_objects %>

app/views/admin/positions/edit.js.erb
$("#positions-modal-content")
  .html("<%= escape_javascript(render 'edit', position: @entity_object ) %>");
$("#positions-modal").modal();

app/views/admin/positions/index.html.erb
<%= render 'admin/header', selected: 'positions' %>

<h2>
  <span>Positions</span>
  <span>
    <%= link_to new_admin_position_path, remote: true, class: 'btn btn-primary pull-right' do %>
      <span class="glyphicon glyphicon-plus"></span> New Position
    <% end %>
  </span>
</h2>

<div id="positions-content">
  <%= render 'index', positions: @all_entity_objects %>
</div>

<!-- Modal -->
<div class="modal fade" id="positions-modal" role="dialog">
  <div class="modal-dialog modal-md">
    <div id="positions-modal-content" class="modal-content"></div>
  </div>
</div>

app/views/admin/positions/new.js.erb
$("#positions-modal-content")
  .html("<%= escape_javascript(render 'new', position: @entity_object ) %>");
$("#positions-modal").modal();

app/views/admin/positions/update.js.erb
<%= render 'reload', position: @entity_object, positions: @all_entity_objects %>