config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'authentication' }

  root 'home#index'

  namespace :directory do
    resources :profiles, only: [:index, :show]
    resources :practices, only: [:index, :show]
  end

  namespace :admin do
    resources :users, except: [:show] do
      get 'delete'
      get 'roles'
      post 'update_roles'
    end
    resources :positions, except: [:show] do
      get 'delete'
    end
    resources :practices, except: [:show] do
      get 'delete'
      resources :memberships, path: :members, except: [:show] do
        get 'delete'
      end
    end
    resources :videos do
      get 'delete'
    end
  end

  resources :videos do
    collection do
      get :autocomplete_video_name
      post :search
    end
  end

  # mount Rop::Engine, at: '/guides', as: 'guides'
end

app/views/admin/_header.html.erb
<h1>ADMIN DASHBOARD</h1>

<ul class="nav nav-tabs">
  <% if valid_admin? %>
    <li role="presentation" class="<%= 'active' if selected == 'users' %>">
      <%= link_to 'Users', admin_users_path %>
    </li>
    <li role="presentation" class="<%= 'active' if selected == 'positions' %>">
      <%= link_to 'Positions', admin_positions_path %>
    </li>
  <% end %>
  <% if valid_practice_lead? %>
    <li role="presentation" class="<%= 'active' if selected == 'practices' %>">
      <%= link_to 'Practices', admin_practices_path %>
    </li>
  <% end %>
  <% if valid_content_admin? %>
    <li role="presentation" class="<%= 'active' if selected == 'videos' %>">
      <%= link_to 'Videos', admin_videos_path %>
    </li>
  <% end %>
</ul>