config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'authentication' }

  root 'home#index'

  namespace :directory do
    resources :profiles, only: [:index, :show]
    resources :practices, only: [:index, :show]
  end

  namespace :admin do
    resources :users, except: [:show] do
      get 'delete'
      get 'roles'
      post 'update_roles'
    end
    resources :positions, except: [:show] do
      get 'delete'
    end
    resources :practices, except: [:show] do
      get 'delete'
      resources :memberships, path: :members, except: [:show] do
        get 'delete'
      end
    end
    resources :videos do
      get 'delete'
    end
  end

  resources :videos do
    collection do
      get :autocomplete_video_name
      post :search
    end
  end

  # mount Rop::Engine, at: '/guides', as: 'guides'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :practices, through: :memberships
  belongs_to :position
  belongs_to :personnel_manager, class_name: 'User'
  has_many :subordinates, class_name: 'User', foreign_key: 'personnel_manager_id'
  has_many :practices_leading, class_name: 'Practice', foreign_key: 'practice_lead_id'
  has_many :videos

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, omniauth_providers: [:google_oauth2]

  royce_roles [
    :admin,
    :personnel_manager,
    :practice_lead,
    :content_admin
  ]

  validates :name, presence: true
  validates :last_name, presence: true
  validates :email, format: {
    with: /\A[A-Z0-9a-z]+@(growthaccelerationpartners|wearegap)\.com\z/,
    message: "has invalid GAP account"
  }

  scope :active, -> { where(active: true) }
  scope :ordered, -> { order(:name, :last_name) }

  def password_required?
    new_record? ? false : super
  end

  def full_name
    "#{name} #{last_name}"
  end

  def personnal_manager_name
    personnel_manager.full_name if personnel_manager
  end

  def position_level
    "#{position.name} #{level}" if position
  end

  def profile_image
    image || 'default.png'
  end

  def profile_icon
    picture || 'default.png'
  end

  def can_manage_practice?(practice_id)
    admin? || (practice_lead? && lead_practice?(practice_id))
  end

  private

  def lead_practice?(practice_id)
    practices_leading.find { |practice| practice.id == practice_id }
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  include DefaultCrud

  before_action :authenticate_user!
  before_action :admin_access?
  before_action :load_personnel_managers, only: [:new, :edit]

  def roles
    load_entity_object_by_id
    @roles = User.available_role_names
  end

  def update_roles
    load_entity_object_by_id
    update_user_roles
  end

  private

  def entity_parameters
    params
      .require(:user)
      .permit(:name, :last_name, :email, :position_id, :level, :personnel_manager_id,
        :employee_type, :location, :active)
  end

  def load_entity_object_by_id
    @entity_object = entity.find(params[:user_id])
  end

  def load_all_entity_objects
    @all_entity_objects = entity.includes(:personnel_manager, :subordinates, :position)
  end

  def load_personnel_managers
    @personnel_managers = @entity_object ? other_personnel_managers : all_personnel_managers
  end

  def all_personnel_managers
    User.active.ordered.personnel_managers
  end

  def other_personnel_managers
    all_personnel_managers.reject { |user| user == @entity_object }
  end

  def update_user_roles
    params[:roles].each do |role, value|
      value == 'true' ? @entity_object.add_role(role) : @entity_object.remove_role(role)
    end
  end

end

app/views/admin/users/_delete.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Delete User</h4>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure that you want to delete this record: <b><%= user.full_name %></b>?
</div>
<div class="modal-footer">
  <%= link_to 'Cancel', '#', class: 'btn btn-default', data: { dismiss: 'modal' } %>
  <%= link_to 'Delete User', admin_user_path(user), method: :delete, remote: true,
    class: 'btn btn-danger' %>
</div>

app/views/admin/users/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Edit User</h4>
</div>
<div>
  <%= render 'form', user: user, personnel_managers: personnel_managers %>
</div>

app/views/admin/users/_index.html.erb
<table id="users-table" class="table table-striped table-bordered" width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Personnel Manager</th>
      <th>Employees</th>
      <th>Employee Type</th>
      <th>Location</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% users.each do |user| %>
    <tr class="<%= 'warning' unless user.active %>">
      <td><%= user.full_name %></td>
      <td><%= user.position_level %></td>
      <td><%= user.personnal_manager_name %></td>
      <td><%= user.subordinates.size %></td>
      <td><%= user.employee_type %></td>
      <td><%= user.location %></td>
      <td>
        <%= link_to admin_user_roles_path(user), remote: true,
          class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-cog"></span> Roles
        <% end %>
        <%= link_to edit_admin_user_path(user), remote: true,
          class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= link_to admin_user_delete_path(user), remote: true,
          class: 'btn btn-danger btn-sm' do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<script type="text/javascript">
  $(document).ready(function() {
     $('#users-table').DataTable({
       retrieve: true,
       iDisplayLength: 50,
       columns: [
         { type: "string" },
         { type: "string" },
         { type: "string" },
         { type: "string" },
         { type: "string" },
         { type: "string" },
         { orderable: false }
       ]
    });
  });
</script>

app/views/admin/users/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">New User</h4>
</div>
<div>
  <%= render 'form', user: user, personnel_managers: personnel_managers %>
</div>

app/views/admin/users/_reload.html.erb
$("ul.errors").html("")
<% if user.errors.any? %>
  <% user.errors.full_messages.each do |message| %>
    $("div.errors").append($("<div class='alert alert-danger'/>").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $("#users-content").html("<%= escape_javascript(render 'index', users: users ) %>");
  $("#users-modal").modal("hide");
<% end %>

app/views/admin/users/_roles.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Edit Roles</h4>
</div>
<%= form_tag(admin_user_update_roles_path(user), remote: true) do %>
  <div class="modal-body">
    <div class="errors"></div>
    <% roles.each do |role|%>
      <div class="checkbox">
        <%= hidden_field_tag "roles[#{role}]", '' %>
        <label>
          <%= check_box_tag "roles[#{role}]", 'true', user.has_role?(role) %>
          <%= role.titleize %>
        </label>
      </div>
    <% end %>
  </div>
  <div class="modal-footer">
    <%= submit_tag 'Update Roles', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn', data: { dismiss: 'modal' } %>
  </div>
<% end %>

app/views/admin/users/create.js.erb
<%= render 'reload', user: @entity_object, users: @all_entity_objects %>

app/views/admin/users/delete.js.erb
$("#users-modal-content")
  .html("<%= escape_javascript(render 'delete', user: @entity_object ) %>");
$("#users-modal").modal();

app/views/admin/users/edit.js.erb
$("#users-modal-content")
  .html("<%= escape_javascript(render 'edit', user: @entity_object, personnel_managers: @personnel_managers) %>");
$("#users-modal").modal();

app/views/admin/users/index.html.erb
<%= render 'admin/header', selected: 'users' %>

<h2>
  <span>Users</span>
  <span>
    <%= link_to new_admin_user_path, remote: true, class: 'btn btn-primary pull-right' do %>
      <span class="glyphicon glyphicon-plus"></span> New User
    <% end %>
  </span>
</h2>

<div id="users-content">
  <%= render 'index', users: @all_entity_objects %>
</div>

<!-- Modal -->
<div class="modal fade" id="users-modal" role="dialog">
  <div class="modal-dialog modal-md">
    <div id="users-modal-content" class="modal-content"></div>
  </div>
</div>

app/views/admin/users/new.js.erb
$("#users-modal-content")
  .html("<%= escape_javascript(render 'new', user: @entity_object, personnel_managers: @personnel_managers) %>");
$("#users-modal").modal();

app/views/admin/users/roles.js.erb
$("#users-modal-content")
  .html("<%= escape_javascript(render 'roles', user: @entity_object, roles: @roles ) %>");
$("#users-modal").modal();

app/views/admin/users/update.js.erb
<%= render 'reload', user: @entity_object, users: @all_entity_objects %>

app/views/admin/users/update_roles.js.erb
$("#users-modal").modal("hide");