config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'authentication' }

  root 'home#index'

  namespace :directory do
    resources :profiles, only: [:index, :show]
    resources :practices, only: [:index, :show]
  end

  namespace :admin do
    resources :users, except: [:show] do
      get 'delete'
      get 'roles'
      post 'update_roles'
    end
    resources :positions, except: [:show] do
      get 'delete'
    end
    resources :practices, except: [:show] do
      get 'delete'
      resources :memberships, path: :members, except: [:show] do
        get 'delete'
      end
    end
    resources :videos do
      get 'delete'
    end
  end

  resources :videos do
    collection do
      get :autocomplete_video_name
      post :search
    end
  end

  # mount Rop::Engine, at: '/guides', as: 'guides'
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  belongs_to :practice

  scope :active, -> { where(active: true) }

  self.per_page = 9

  def presenter
    user.full_name
  end

  def thumbnail
    "http://img.youtube.com/vi/#{video_id}/hqdefault.jpg"
  end

  def embedded_link
    url.gsub!('watch?v=', 'embed/')
  end

  private

  def video_id
    url.split('v=').last.split('?').first
  end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  include DefaultCrud

  before_action :authenticate_user!
  before_action :content_admin_access?
  before_action :load_practices, only: [:new, :edit]
  before_action :load_users, only: [:new, :edit]

  private

  def entity_parameters
    params.require(:video).permit(:name, :url, :description, :active, :tags, :practice_id, :user_id)
  end

  def load_entity_object_by_id
    @entity_object = entity.find(params[:video_id])
  end

  def load_all_entity_objects
    @all_entity_objects = entity.includes(:user, :practice).order(:name)
  end

  def load_practices
    @practices = Practice.all
  end

  def load_users
    @users = User.active.ordered
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  add_breadcrumb 'Videos', :videos_path

  before_action :authenticate_user!

  autocomplete :video, :name, full: true

  def index
    @videos = Video.active.all.includes(:user).paginate(page: params[:page])
  end

  def show
    @video = Video.active.find(params[:id])
    add_breadcrumb @video.name, video_path(@video)
  end

  def search
    @videos = Video.active.where(search_param).paginate(page: params[:page])
  end

  private

  def search_param
    ['lower(name) like ?', "%#{params[:search].downcase}%"]
  end
end

app/views/admin/videos/_delete.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Delete Video</h4>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure that you want to delete this record: <b><%= video.name %></b>?
</div>
<div class="modal-footer">
  <%= link_to 'Cancel', '#', class: 'btn btn-default', data: { dismiss: 'modal' } %>
  <%= link_to 'Delete Video', admin_video_path(video), method: :delete, remote: true,
    class: 'btn btn-danger' %>
</div>

app/views/admin/videos/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Edit Video</h4>
</div>
<div>
  <%= render 'form', video: video, practices: practices, users: users %>
</div>

app/views/admin/videos/_form.html.erb
<%= form_for [:admin, video], remote: true, html: { style: 'display:inline;' } do |f| %>
  <div class="modal-body">
    <div class="errors"></div>
    <div class="form-group">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :url, 'Link', class: 'control-label' %>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description, class: 'control-label' %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class='row'>
      <div class="form-group col-sm-6">
        <%= f.label :practice_id, class: 'control-label' %>
        <%= f.collection_select(:practice_id, practices, :id, :name,
          { include_blank: true }, { class: 'form-control' }) %>
      </div>
      <div class="form-group col-sm-6">
        <%= f.label :user_id, 'Presenter', class: 'control-label' %>
        <%= f.collection_select(:user_id, users, :id, :full_name,
          { include_blank: true }, { class: 'form-control' }) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.check_box :active %>
      <%= f.label :active, class: 'control-label' %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn', data: { dismiss: 'modal' } %>
  </div>
<% end %>

app/views/admin/videos/_index.html.erb
<table id="videos-table" class="table table-striped table-bordered" width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Link</th>
      <th>Presenter</th>
      <th>Practice</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% videos.each do |video| %>
    <tr class="<%= 'warning' unless video.active %>">
      <td><%= link_to video.name, video_path(video) %></td>
      <td><%= video.url %></td>
      <td><%= video.presenter %></td>
      <td><%= video.practice.name %></td>
      <td>
        <%= link_to edit_admin_video_path(video), remote: true,
          class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= link_to admin_video_delete_path(video), remote: true,
          class: 'btn btn-danger btn-sm' do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<script type="text/javascript">
  $(document).ready(function() {
     $('#videos-table').DataTable({
       retrieve: true,
       iDisplayLength: 50,
       columns: [
         { type: "string" },
         { type: "string" },
         { type: "string" },
         { type: "string" },
         { orderable: false }
       ]
    });
  });
</script>

app/views/admin/videos/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">New Video</h4>
</div>
<div>
  <%= render 'form', video: video, practices: practices, users: users %>
</div>

app/views/admin/videos/_reload.html.erb
$("ul.errors").html("")
<% if video.errors.any? %>
  <% video.errors.full_messages.each do |message| %>
    $("div.errors").append($("<div class='alert alert-danger'/>").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $("#videos-content").html("<%= escape_javascript(render 'index', videos: videos ) %>");
  $("#videos-modal").modal("hide");
<% end %>

app/views/admin/videos/create.js.erb
<%= render 'reload', video: @entity_object, videos: @all_entity_objects %>

app/views/admin/videos/delete.js.erb
$("#videos-modal-content")
  .html("<%= escape_javascript(render 'delete', video: @entity_object ) %>");
$("#videos-modal").modal();

app/views/admin/videos/destroy.js.erb
<%= render 'reload', video: @entity_object, videos: @all_entity_objects %>

app/views/admin/videos/edit.js.erb
$("#videos-modal-content")
  .html("<%= escape_javascript(render 'edit', video: @entity_object, practices: @practices, users: @users) %>");
$("#videos-modal").modal();

app/views/admin/videos/index.html.erb
<%= render 'admin/header', selected: 'videos' %>

<h2>
  <span>Videos</span>
  <span>
    <%= link_to new_admin_video_path, remote: true, class: 'btn btn-primary pull-right' do %>
      <span class="glyphicon glyphicon-plus"></span> New Video
    <% end %>
  </span>
</h2>

<div id="videos-content">
  <%= render 'index', videos: @all_entity_objects %>
</div>

<!-- Modal -->
<div class="modal fade" id="videos-modal" role="dialog">
  <div class="modal-dialog modal-md">
    <div id="videos-modal-content" class="modal-content"></div>
  </div>
</div>

app/views/admin/videos/new.js.erb
$("#videos-modal-content")
  .html("<%= escape_javascript(render 'new', video: @entity_object, practices: @practices, users: @users) %>");
$("#videos-modal").modal();

app/views/admin/videos/update.js.erb
<%= render 'reload', video: @entity_object, videos: @all_entity_objects %>